local tbl = {
	name = "The Seat of Sacrifice",
	mesh = "[KDF] - The Seat of Sacrifice",
	dutyid = 922,
	level = 80,
	expansion = 5,
	creator = "Kitanoi",
	notes = "Requires 8 characters.\n\n2 tanks, 2 healers, 4 dps (ranged ideally)\n\nThere will be wipes.\nFalling meteors and Sword of Light aren't detected so you need to run until favorable locations are used.",
	queuetype = 2,
	FFA = false,
	hacks = false,
	requeuetimer = 10,
	objectivedestinations = {
		[1] = {objective = 1, pos = {x = 100, y = 0, z = 100}},
	},
	interacts = {},
	bossids = {
		9462, -- Warrior of Light -- Shadowbringers Warrior of Light Card
	},
	forcemeleerange = {},
	enemytargetdistance = 50,
	prioritytarget = {
		[1] = {contentid = 8531, priority = 1, type = "Gaol"},
	},
	avoidentity = {},
	tankat = {},
	advancedavoid = {
		[1] = {type = "custom", customdetails = "libraryfunction", functioncode = "KitanoiFuncs.WoLStory()"},
		[2] = {
			castingid = 16722,
			pos = {
				[1] = {x = 92.5, y = 0, z = 92.5},
				[2] = {x = 92.5, y = 0, z = 107.5},
				[3] = {x = 107.5, y = 0, z = 92.5},
				[4] = {x = 107.5, y = 0, z = 107.5},
				[5] = {x = 100, y = 0, z = 110},
				[6] = {x = 110, y = 0, z = 100},
				[7] = {x = 100, y = 0, z = 90},
				[8] = {x = 90, y = 0, z = 100},
			},
			type = "multifixed",
		},
		[3] = {
			castingid = 17811,
			pos = {
				[1] = {x = 92.5, y = 0, z = 92.5},
				[2] = {x = 92.5, y = 0, z = 107.5},
				[3] = {x = 107.5, y = 0, z = 92.5},
				[4] = {x = 107.5, y = 0, z = 107.5},
				[5] = {x = 100, y = 0, z = 110},
				[6] = {x = 110, y = 0, z = 100},
				[7] = {x = 100, y = 0, z = 90},
				[8] = {x = 90, y = 0, z = 100},
			},
			type = "multifixed",
		},
		[4] = {
			castingid = 16744,
			pos = {
				[1] = {x = 92.5, y = 0, z = 92.5},
				[2] = {x = 92.5, y = 0, z = 107.5},
				[3] = {x = 107.5, y = 0, z = 92.5},
				[4] = {x = 107.5, y = 0, z = 107.5},
				[5] = {x = 100, y = 0, z = 110},
				[6] = {x = 110, y = 0, z = 100},
				[7] = {x = 100, y = 0, z = 90},
				[8] = {x = 90, y = 0, z = 100},
			},
			type = "multifixed",
		},
	},
	hasbuff = {},
	overheadmarkers = {
		[1] = {
			contentid = "9462",
			desc = "ice marker",
			detectwho = "any",
			id = 225,
			pos = {},
			returnpos = {},
			timetoreturn = 5,
			type = "justrecord",
		},
		[2] = {
			contentid = "9462",
			desc = "single arrow marker",
			detectwho = "any",
			id = 87,
			returnpos = {},
			timetoreturn = 8,
			type = "justrecord",
		},
		[3] = {
			contentid = "9462",
			desc = "stakc marker",
			detectwho = "any",
			id = 161,
			returnpos = {},
			timetoreturn = 8,
			type = "justrecord",
		},
		[4] = {
			contentid = "9462",
			desc = "red markers",
			detectwho = "any",
			id = 234,
			returnpos = {},
			timetoreturn = 8,
			type = "justrecord",
		},
		[5] = {
			contentid = "9462",
			desc = "big purple markers",
			detectwho = "any",
			id = 233,
			returnpos = {},
			timetoreturn = 8,
			type = "justrecord",
		},
	},
	excludeavoid = {20250,20251},
	puddledata = {},
	dontcastwhenmoving = true,
}

return tbl