local tbl = {
	name = "A Relic Reborn: the Hydra",
	mesh = "Hall of the Bestiarii",
	dutyid = 369,
	level = 50,
	expansion = 2,
	creator = "Koyote#6642",
	notes="",
	queuetype = 2,
	requeuetimer = 10,
	objectivedestinations = {},
	forcemeleerange = {},
	interactdistance = 20,
	interacts = {},
	enemytargetdistance = 100,
	bossids = {2161},
	prioritytargetdistance = 10,
	prioritytarget = {},
	advancedavoid = {},
	hasbuff = {},
	overheadmarkers = {},
	excludeavoid = {},
	pullenemyoutofpuddle = false,
}

return tbl