local tbl = {
	name = "A Relic Reborn: the Chimera",
	mesh = "The Weeping Saint",
	dutyid = 368,
	level = 50,
	expansion = 2,
	creator = "Koyote#6642",
	notes="",
	queuetype = 2,
	requeuetimer = 10,
	objectivedestinations = {},
	forcemeleerange = {},
	interactdistance = 20,
	interacts = {},
	enemytargetdistance = 30,
	bossids = {2162},
	prioritytargetdistance = 10,
	prioritytarget = {},
	advancedavoid = {},
	hasbuff = {},
	overheadmarkers = {},
	excludeavoid = {},
	pullenemyoutofpuddle = false,
}

return tbl